# Spring Boot Application.configuration
spring:
  profiles:
    active: production
  # Database
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: nedim
  # JPA properties
  jpa:
    hibernate:
      generate-ddl: true
      ddl-auto: update
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false